### ISSUE TITLE
Beta release final task list

### ISSUE THREAD

**Issue by falkTX** [AidaDSP/AIDA-X#8]
Keeping track of the last few details to handle

- [x] repo name as AIDA-X
- [x] Windows standalone not set as win32 gui application (shows console)
- [x] Windows standalone freezes when changing buffer size
- [x] Windows installer does not create start menu entry
- [x] macOS app bundle (from CI artifacts) is not executable, due to zip usage
- [x] MOD Neural Amp landing page public
- [x] MOD wasm build does not handle high-dpi scaling properly
- [x] MOD wasm needs meters adjustment and decision
- [x] MOD wasm final audio loops
